import React from 'react';
import JobComponent from './JobComponent/JobComponent';
const JobLists = () => {
  const AllJobs = [
    {
      rank:1,
      newsUrl:"https://christianselig.com/2024/02/introducing-juno/",
      newsHeading:"Juno - A Youtube Client for Vision Pro",
      srcUrl:"https://news.ycombinator.com/from?site=christianselig.com",
      srcName:"christianselig.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 163,
    },
    {
      rank:2,
      newsUrl:"https://www.modulaware.com/mdlt69.htm",
      newsHeading:"Juice – Oberon JIT browser plugin (1996)",
      srcUrl:"https://news.ycombinator.com/from?site=modulaware.com",
      srcName:"modulaware.com",
      subScore:13,
      posterName:"cylinder714",
      timePosted:1,
      commetsCount: 4,
    },
    {
      rank:3,
      newsUrl:"https://tembo.io/blog/tembo-data-warehouse",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=tembo.io",
      srcName:"tembo.io",
      subScore:78,
      posterName:"samaysharma",
      timePosted:4,
      commetsCount: 27,
    },
    {
      rank:4,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:5,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:6,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:7,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:8,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:9,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:10,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:11,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:12,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:13,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:14,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"The Retro Web – Database, Docs, BIOS, Drivers, etc. for old PC Hardware",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
    {
      rank:15,
      newsUrl:"https://theretroweb.com/",
      newsHeading:"We built our customer data warehouse all on Postgres",
      srcUrl:"https://news.ycombinator.com/from?site=theretroweb.com",
      srcName:"theretroweb.com",
      subScore:132,
      posterName:"axxl",
      timePosted:5,
      commetsCount: 9,
    },
  ]
  return (
    <>
      {AllJobs.map((jobDetail)=>(
        <JobComponent jobDetail={jobDetail}/>
      ))}
    </>
  )
}

export default JobLists